[package]
name = "bevy_dasp_breakout"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = "0.10.1"
cpal = "0.12"
dasp = { version = "0.11.0", features = ["all"] }
rand = "0.8.5"
